### PR TITLE
Use correct isoCode for Sweden and fix some translations

### PR DESCRIPTION
**Pull request by lanker**

### CODE REVIEW

**Comment by B0und** [comment]
Thank you for your contribution!

**Comment by lanker** [comment]
Hey, just checking in, was the intention to merge this?

**Comment by B0und** [comment]
> Hey, just checking in, was the intention to merge this?

If you could revert the ISO code change, i would gladly merge this. (Or i guess i could make another PR myself, but only with translations)

**Comment by lanker** [comment]
Are there any problems with the iso code commit? Is that the reason for the failing checks? Seems to not be possible to access the logs for the check without a vercel account.

**Comment by B0und** [comment]
> Are there any problems with the iso code commit? Is that the reason for the failing checks? Seems to not be possible to access the logs for the check without a vercel account.

It breaks article preview

**Comment by lanker** [comment]
Indeed it did. I guess we need to convert country code to language code and instead use that for picking the correct wikipedia. Added a commit for that.

**Comment by B0und** [comment]
> Indeed it did. I guess we need to convert country code to language code and instead use that for picking the correct wikipedia. Added a commit for that.

i left a comment in the code with a fix, since article preview still doesnt work, if your user interface language and wiki language are different.

**Comment by lanker** [comment]
> i left a comment in the code with a fix, since article preview still doesnt work, if your user interface language and wiki language are different. Can you add it and test that it works? [#17 (files)](https://github.com/B0und/WikiSpeedrun/pull/17/files#diff-7c243ee1ef34e493bb8d64f1da5e2f51f393fb090f1c3c39a7612d871a648610R49)

Oh, sorry, thought I tested all cases, I'll take another look. However, I don't see your comment, forgot to submit it?

**Review by B0und — CHANGES_REQUESTED** [review]

**Comment by B0und** [comment]
> > i left a comment in the code with a fix, since article preview still doesnt work, if your user interface language and wiki language are different. Can you add it and test that it works? [#17 (files)](https://github.com/B0und/WikiSpeedrun/pull/17/files#diff-7c243ee1ef34e493bb8d64f1da5e2f51f393fb090f1c3c39a7612d871a648610R49)
> 
> Oh, sorry, thought I tested all cases, I'll take another look. However, I don't see your comment, forgot to submit it?
> 

Oops, my bad. They should be visible now

**Review by B0und — APPROVED** [review]
LGTM

**Comment by B0und** [comment]
Thanks for your help!

**Comment by lanker** [comment]
I noticed that it generates an exception if the `interfaceLanguage` setting in local storage is set to an invalid locale (`sv` in this case, which was changed to `se` in this PR), sorry for not catching that earlier. Tried to figure out a fix but I'm slightly lost in all the hooks...

Anyhow, the exception:

```
Uncaught (in promise) TypeError: localeTranslationLoaders[locale] is not a function
    importLocaleAsync i18n-util.async.ts:28
    loadLocaleAsync i18n-util.async.ts:31
    LocaleProvider LocaleProvider.tsx:22
```

**Comment by B0und** [comment]
> I noticed that it generates an exception if the `interfaceLanguage` setting in local storage is set to an invalid locale (`sv` in this case, which was changed to `se` in this PR), sorry for not catching that earlier. Tried to figure out a fix but I'm slightly lost in all the hooks...
> 
> Anyhow, the exception:
> 
> ```
> Uncaught (in promise) TypeError: localeTranslationLoaders[locale] is not a function
>     importLocaleAsync i18n-util.async.ts:28
>     loadLocaleAsync i18n-util.async.ts:31
>     LocaleProvider LocaleProvider.tsx:22
> ```

pushed a fix to prod, let me know if it helps (old user settings should be reset now)

**Comment by lanker** [comment]
> pushed a fix to prod, let me know if it helps (old user settings should be reset now)

Yep, that did it!

**Pull request merged**
